-- DevsHub Academy - production database foundation
-- Target: PostgreSQL / Supabase

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  status text not null default 'active'
    check (status in ('active','suspended','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'admin'
    check (role in ('owner','admin','issuer','viewer')),
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  code text,
  status text not null default 'active'
    check (status in ('active','inactive','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, code)
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  full_name text not null,
  email text,
  external_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  student_id uuid references public.students(id) on delete set null,
  course_id uuid references public.courses(id) on delete set null,

  serial text not null unique,
  student_name text not null,
  course_name text not null,

  issued_at date not null default current_date,
  expires_at date,
  status text not null default 'valid'
    check (status in ('valid','revoked','expired')),

  pdf_url text,
  verification_path text,
  metadata jsonb not null default '{}'::jsonb,

  revoked_at timestamptz,
  revoked_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (
    (status <> 'revoked')
    or revoked_at is not null
  )
);

create index if not exists certificates_organization_id_idx
  on public.certificates (organization_id);

create index if not exists certificates_status_idx
  on public.certificates (status);

create index if not exists certificates_issued_at_idx
  on public.certificates (issued_at desc);

create table if not exists public.verification_logs (
  id bigint generated by default as identity primary key,
  certificate_id uuid references public.certificates(id) on delete set null,
  serial text not null,
  result text not null
    check (result in ('valid','revoked','expired','not_found','error')),
  source text not null default 'serial'
    check (source in ('serial','qr','direct_link')),
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists verification_logs_serial_idx
  on public.verification_logs (serial);

create index if not exists verification_logs_created_at_idx
  on public.verification_logs (created_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_organization_idx
  on public.audit_logs (organization_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists organizations_set_updated_at on public.organizations;
create trigger organizations_set_updated_at
before update on public.organizations
for each row execute function public.set_updated_at();

drop trigger if exists courses_set_updated_at on public.courses;
create trigger courses_set_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists students_set_updated_at on public.students;
create trigger students_set_updated_at
before update on public.students
for each row execute function public.set_updated_at();

drop trigger if exists certificates_set_updated_at on public.certificates;
create trigger certificates_set_updated_at
before update on public.certificates
for each row execute function public.set_updated_at();

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.courses enable row level security;
alter table public.students enable row level security;
alter table public.certificates enable row level security;
alter table public.verification_logs enable row level security;
alter table public.audit_logs enable row level security;

-- No public RLS policies are created yet.
-- The server-side API uses the Supabase service-role key.
-- User-facing policies will be added during the authentication phase.

insert into public.organizations (name, slug)
values ('DevsHub Academy', 'devshub-academy')
on conflict (slug) do update set name = excluded.name;

insert into public.certificates (
  organization_id,
  serial,
  student_name,
  course_name,
  issued_at,
  status,
  verification_path
)
select
  o.id,
  'DVH-2026-78421',
  'Ahmed Ali',
  'Web Development Essentials',
  date '2026-09-12',
  'valid',
  '/#certificate/DVH-2026-78421'
from public.organizations o
where o.slug = 'devshub-academy'
on conflict (serial) do nothing;
